1. Array reversal


In [2]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    # Arrays in Python - Hacker Rank Solution START
    return(numpy.array(arr[::-1], float))
    # Arrays in Python - Hacker Rank Solution END


In [3]:
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


2.shape nad reshape 

In [4]:
import numpy
print(numpy.array(input().split(), int).reshape(3, 3))


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


3.Transpose nad Flatten

In [10]:
import numpy
n, m = map(int, input().split())

storage = numpy.array([input().strip().split() for _ in range(n)], int)
print (storage.transpose())
print (storage.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


4. Concatenate

In [12]:
import numpy
P, N, M = map(int,input().split())
A = numpy.array([input().split() for _ in range(P)],int)
B = numpy.array([input().split() for _ in range(N)],int)
print(numpy.concatenate((A, B), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


5. Zeroes and ones 

In [13]:
size = tuple(map(int,input().strip().split()))
print( numpy.zeros(size, int) )
print( numpy.ones(size, int) )
                    

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


6. Identity and Eye matrix

In [15]:
import numpy
N,M = map(int,input().split())
print (numpy.eye(N,M))



3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. ceil, floor and rint

In [1]:
import numpy

numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


8. Sum and prod

In [4]:
import numpy

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))


2 2
1 2
3 4
24


9.Min and Max

In [5]:

import numpy

N, M = map(int, input().split())
storage = numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(storage, axis=1), axis=0))


4 2
2 5
3 7
1 3
4 0
3


10. mean var and std

In [6]:
import numpy

N,M = map(int, input().split())
l = []

for i in range(N):
    a = list(map(int, input().split()))
    l.append(a)

l = numpy.array(l)

numpy.set_printoptions(legacy='1.13')
print(numpy.mean(l, axis = 1))
print(numpy.var(l, axis = 0))
print(numpy.std(l))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


11. dot and cross

In [7]:
import numpy

n = int(input())
a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(a, b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


12. inner and outer

In [8]:
import numpy

A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)
print(numpy.inner(A, B), numpy.outer(A, B), sep='\n')

0 1 
2 3
3
[[0 0]
 [2 3]]


13. Polynomials

In [9]:
import numpy

poly = [float(x) for x in input().split()]
x = float(input())

print(numpy.polyval(poly, x))

1.1 2 3
0
3.0


14. Linear algebra

In [10]:
import numpy
N = int(input())
A = numpy.array([input().split() for _ in range(N)], float)
print(round(numpy.linalg.det(A),2))

2
1.1 1.1
1.1 1.1
0.0
